# Generated by Django 5.2.3 on 2025-06-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date', 'project__name'], 'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
    ]
